# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines #master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  inputs:
    displayName: 'Generate Pester Analysis'
    targetType: 'inline' # Optional. Options: filePath, inline
    #filePath: # Required when targetType == FilePath
    #arguments: # Optional
    script: "Invoke-Pester @{Path= './tests/*.tests.ps1' ;Parameters = @{Answer='41'}} -OutputFile TEST-HHGTTG.xml -OutputFormat NUnitXML -EnableExit" # Required when targetType == Inline
    #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    failOnStderr: true # Optional
    #ignoreLASTEXITCODE: false # Optional
    #pwsh: false # Optional
    #workingDirectory: # Optional
    timeoutInMinutes: 1

- task: PublishTestResults@2
  inputs:
    displayName: 'Publish Pester results'
    testResultsFormat: 'NUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/TEST-*.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional
    continueOnError: true
    timeoutInMinutes: 1
